FROM mcr.microsoft.com/dotnet/sdk:10.0.401 AS build
WORKDIR /source
COPY . .
RUN dotnet publish src/Platform.Api/Platform.Api.csproj -c Release -o /out
FROM mcr.microsoft.com/dotnet/aspnet:10.0.12
WORKDIR /app
COPY --from=build /out .
USER 1654
ENTRYPOINT ["dotnet", "Platform.Api.dll"]
